# Linear regression

This is an explanation on how to use pytorch for linear regression using the pytorch neural network module.

In [1]:
import numpy as np
import torch as tf
import torch.nn as nn
import matplotlib.pyplot as plt

#### Dataset creation
***

The equation that we are going to use to do the liner regression will be :
\begin{align*}
y = 2x + 1
\end{align*}

Generating the independant variable x and dependant variable y. Then converting the *list* --> *numpy array* --> *torch tensors.*

In [2]:
x = [i for i in range(11)]
x = np.array(x, dtype=np.float32) #float data type required for gradients
x = tf.from_numpy(x)
x_train = x.view(-1,1) # To take the transpose
print(x_train)

tensor([[ 0.],
        [ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])


In [3]:
y = [2*i+1 for i in range(11)]
y = np.array(y, dtype=np.float32)
y = tf.from_numpy(y)
y_train = y.view(-1,1)
print(y_train)

tensor([[ 1.],
        [ 3.],
        [ 5.],
        [ 7.],
        [ 9.],
        [11.],
        [13.],
        [15.],
        [17.],
        [19.],
        [21.]])


#### Model building
***

We are going to define a class named _LinearRegression_ and then code the forward pass into it. Normally while creating a class we define __init__ for initilisation purposes(more details [here](https://www.youtube.com/watch?v=WIP3-woodlU)). In the case of multiple inheritance, we define _super()_ function to make sure that the __init__ of the parent class would be called only once(more details [here](https://www.youtube.com/watch?v=zS0HyfN7Pm4)).

The input arguments to the pytorch linear module is in form _Linear(input_dim, output_dim)_ , which means input_dim total size of the input features and output_dim the number of output classes. So if we have a 28X28 image passing as input with 10 class, then input_dim = 784 and output_dim = 10(more details [here](https://mc.ai/pytorch-layer-dimensions-what-sizes-should-they-be-and-why/) and [here](https://towardsdatascience.com/pytorch-layer-dimensions-what-sizes-should-they-be-and-why-4265a41e01fd)).

We are going to instantiate the model, since ours is simple straight line equation the x value will be a single value and output y will also be single value. Hence the input_dim and output_dim are both 1. This linear regression will model the data in the form of

$ y = Ax + c $

The A being the weight matrix that transforms the input x with a bias c to produce the output(more details [here](https://www.youtube.com/watch?v=rcc86nXKwkw)).


In [4]:
input_dim = 1
output_dim = 1

model = nn.Linear(input_dim, output_dim)

Creating the loss class. Loss is the difference betweent the model predicted output and original output. The loss is to be calculated and then optimized in such a way that after each training epoch the loss should reduce. Here Mean Square Error is taken for loss calculation.

$MSE = \frac{1}{n}\sum_{i=1}^{n}(\hat{y}-y)$

$\hat{y} - predicted\\$
$y - true value$

In [5]:
criterion = nn.MSELoss()

Next we define the optimizer that can help optimise the loss function such that the loss value is less, meaning the predicted value almost equal to the expected original value.

$\Theta = \Theta-\eta \Delta \underset{\Theta}{}$

In [6]:
learning_rate = 0.01
optimizer = tf.optim.SGD(model.parameters(),lr=learning_rate)

In [9]:
epochs = 100

for epoch in range(1,epochs+1):
    optimizer.zero_grad()  # to clear all values to prevent accumulation from previous epochs
    output = model(x_train) # forward passing
    loss = criterion(output, y_train) # loss calculation wrt to the original output
    loss.backward()
    optimizer.step()
    print("epoch {}, loss {}".format(epoch,loss))

tensor(0.0002, grad_fn=<MseLossBackward>)
<class 'torch.Tensor'>
torch.Size([])
epoch 1, loss 0.00015833428187761456


#### Data comparision
***

In [11]:
predicted = model(x_train) # y = 2x+1
print(predicted)

tensor([[ 1.0234],
        [ 3.0200],
        [ 5.0167],
        [ 7.0133],
        [ 9.0099],
        [11.0066],
        [13.0032],
        [14.9998],
        [16.9964],
        [18.9931],
        [20.9897]], grad_fn=<AddmmBackward>)


In [12]:
print(y_train) # actual output

tensor([[ 1.],
        [ 3.],
        [ 5.],
        [ 7.],
        [ 9.],
        [11.],
        [13.],
        [15.],
        [17.],
        [19.],
        [21.]])


#### Graph plotting
***

In [ ]:
plt.cfg() # to clear the figure

# plotting true data
plt.plot(x_train,y_train,)